version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: meu_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./dados_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
